CSV_COLUMNS:
  HNAP_ATTRIBUTES: [trim, lower, no_null]
  FEATURE_ATTRIBUTES: [trim, no_null]
  METADATA_SECTION: [trim, upper, no_null]
#
CREATE_KEY_VALUE:
#
NO_DUPLICATE:
  DUP_1: [HNAP_ATTRIBUTES]
#
CHECK_DOMAIN:
